replicaCount: 1

image:
  repository: ghcr.io/x0ddf/whodidthat-adm-controller
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

service:
  type: ClusterIP
  port: 8443

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}

cert-manager:
  enabled: false
  crds:
    enabled: true

webhook:
  failurePolicy: Ignore
  timeoutSeconds: 5
  namespaceSelector: {}
  objectSelector: {} 