---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "whodidthat.fullname" . }}-ca-issuer
  labels: {{- include "whodidthat.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "whodidthat.fullname" . }}-ca
  labels: {{- include "whodidthat.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ include "whodidthat.fullname" . }}
  secretName: {{ include "whodidthat.fullname" . }}-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "whodidthat.fullname" . }}-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - {{ include "whodidthat.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "whodidthat.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "whodidthat.fullname" . }}-issuer
  namespace: {{ .Release.Namespace }}
  labels: {{- include "whodidthat.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "whodidthat.fullname" . }}-ca
