apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whodidthat.fullname" . }}
  labels:
    {{- include "whodidthat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "whodidthat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "whodidthat.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "whodidthat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - --port={{ .Values.service.port }}
            - --tls-crt=/etc/webhook/certs/tls.crt
            - --tls-key=/etc/webhook/certs/tls.key
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cert
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: {{ include "whodidthat.fullname" . }}-ca