apiVersion: v1
kind: Service
metadata:
  name: {{ include "whodidthat.fullname" . }}
  labels:
    {{- include "whodidthat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "whodidthat.selectorLabels" . | nindent 4 }} 