apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "whodidthat.fullname" . }}
  labels:
    {{- include "whodidthat.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "whodidthat.fullname" . }}-ca
webhooks:
  - name: whodidthat.{{ .Release.Namespace }}.svc
    admissionReviewVersions: ["v1"]
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    sideEffects: None
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    clientConfig:
      service:
        name: {{ include "whodidthat.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: 443
    rules:
      # Handle built-in resources
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods", "services", "configmaps", "secrets"]
        scope: "Namespaced"
      # Handle CRDs themselves
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apiextensions.k8s.io"]
        apiVersions: ["v1"]
        resources: ["customresourcedefinitions"]
      # Handle all custom resources dynamically
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]  # All API groups
        apiVersions: ["*"]  # All API versions
        resources: ["*"]  # All resources
{{/*      - operations: ["CREATE", "UPDATE"]*/}}
{{/*        apiGroups: ["*"]*/}}
{{/*        apiVersions: ["*"]*/}}
{{/*        resources: ["*"]*/}}
    {{- with .Values.webhook.namespaceSelector }}
    namespaceSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.webhook.objectSelector }}
    objectSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }} 